CREATE OR REPLACE VIEW INTEL_TEST_DB.BMATHUB_ANALYSIS.SIM_BOM AS
SELECT  t1.ITEM,t1.ITEM_CLASS_NM,t1.ANCHOR_ITEM_ID,t1.BOM_NUM,t1.LOC,t2.ITEM_DSC
FROM INTEL_TEST_DB.BMATHUB_XFRM.V_COMPRESS_BOM_CORE AS t1
JOIN INTEL_TEST_DB.BMATHUB_XFRM.V_ITEM_DETAIL_ROOT AS t2 
ON ( t1.ITEM = t2.ITEM_ID)